import type { Project, Experience, Skill, BlogPost, Podcast, Initiative } from "./types";

export const personalInfo = {
  name: "محمد المطيري",
  nameEn: "Mohammed Al-Mutairi",
  title: "رائد أعمال · قائد منتجات · مبتكر تقني",
  titleEn: "Entrepreneur · Product Leader · Tech Innovator",
  bio: `أؤمن أن التقنية أداة لحل مشكلات حقيقية وبناء مستقبل أفضل. أعمل على تقاطع الابتكار التقني والريادة في الأعمال، وأسعى دائماً لإحداث أثر حقيقي في المجتمع والصناعة.`,
  bioEn: `I believe technology is a tool for solving real problems and building a better future. I work at the intersection of tech innovation and entrepreneurship, always striving to create genuine impact in society and industry.`,
  email: "hi@mhmd.sa",
  location: "الرياض، المملكة العربية السعودية",
  locationEn: "Riyadh, Saudi Arabia",
  avatar: "/avatar.jpg",
  social: {
    twitter:   "https://twitter.com/mhmd",
    linkedin:  "https://linkedin.com/in/mhmd",
    github:    "https://github.com/mhmmdalmutairi",
    instagram: "https://instagram.com/mhmd",
    youtube:   "https://youtube.com/@mhmd",
  },
  company: {
    name:        "شركتي",
    nameEn:      "My Company",
    tagline:     "نبني المستقبل الرقمي",
    taglineEn:   "Building the Digital Future",
    description: "شركة متخصصة في تطوير المنتجات الرقمية وتحويل الأفكار إلى واقع ملموس يخدم ملايين المستخدمين.",
    link:        "https://company.sa",
    founded:     "2020",
  },
  stats: [
    { label: "سنوات خبرة",   value: "٨+",  labelEn: "Years Experience" },
    { label: "مشروع منجز",   value: "٣٠+", labelEn: "Projects Delivered" },
    { label: "مستخدم نشط",  value: "١م+", labelEn: "Active Users" },
    { label: "مبادرة مجتمعية", value: "١٥+", labelEn: "Community Initiatives" },
  ],
};

export const experiences: Experience[] = [
  {
    id:          "1",
    role:        "المؤسس والرئيس التنفيذي",
    company:     "اسم الشركة",
    period:      "٢٠٢٠ – الآن",
    description: "قيادة الشركة في بناء منتجات رقمية مبتكرة تخدم السوق السعودي والخليجي.",
    highlights:  [
      "بناء فريق من ٢٠+ متخصص في التقنية والتصميم والمنتج",
      "إطلاق منتجات وصل مجموع مستخدميها لأكثر من مليون مستخدم",
      "جذب شراكات استراتيجية مع كبرى الشركات المحلية والدولية",
    ],
    current:     true,
    type:        "fulltime",
  },
  {
    id:          "2",
    role:        "مدير المنتج الأول",
    company:     "شركة تقنية رائدة",
    period:      "٢٠١٧ – ٢٠٢٠",
    description: "قيادة استراتيجية المنتج وتطوير خارطة الطريق لمنتجات B2B/B2C.",
    highlights:  [
      "أطلقت ٥ منتجات رئيسية من الصفر حتى الإطلاق",
      "قدت فريق مكوّن من ١٢ مدير منتج",
      "حققت نمو ٢٠٠٪ في الإيرادات خلال ١٨ شهر",
    ],
    type:        "fulltime",
  },
  {
    id:          "3",
    role:        "مستشار تقني",
    company:     "شركات ناشئة متعددة",
    period:      "٢٠١٥ – ٢٠١٧",
    description: "تقديم الاستشارات الاستراتيجية للشركات الناشئة في مجال التقنية والمنتج.",
    highlights:  [
      "استشارة ١٢+ شركة ناشئة في المرحلة الأولى",
      "ساعدت في إغلاق جولات تمويلية بإجمالي ٢٠م+ ريال",
    ],
    type:        "advisory",
  },
  {
    id:          "4",
    role:        "مطور منتجات",
    company:     "بداياتي المهنية",
    period:      "٢٠١٢ – ٢٠١٥",
    description: "بناء المهارات التقنية وتطوير أولى التجارب المهنية في مجال التقنية.",
    highlights:  [
      "تطوير تطبيقات ويب وموبايل من الصفر",
      "العمل مع فرق دولية متعددة الجنسيات",
    ],
    type:        "fulltime",
  },
];

export const projects: Project[] = [
  {
    id:          "1",
    title:       "منصة [اسم المشروع]",
    description: "منصة رقمية متكاملة تحل مشكلة حقيقية في السوق المحلي وتخدم شريحة واسعة من المستخدمين.",
    tags:        ["Next.js", "TypeScript", "AWS", "Product Strategy"],
    featured:    true,
    year:        "2024",
    status:      "completed",
    link:        "#",
  },
  {
    id:          "2",
    title:       "تطبيق [اسم التطبيق]",
    description: "تطبيق موبايل بتجربة مستخدم استثنائية يخدم قطاع [الاسم] في المنطقة.",
    tags:        ["React Native", "Node.js", "MongoDB"],
    featured:    true,
    year:        "2023",
    status:      "completed",
    link:        "#",
  },
  {
    id:          "3",
    title:       "مبادرة [الاسم]",
    description: "مبادرة مجتمعية لدعم [القطاع] وتمكين [الفئة المستهدفة].",
    tags:        ["Community", "Product", "Impact"],
    featured:    false,
    year:        "2023",
    status:      "in-progress",
    link:        "#",
  },
  {
    id:          "4",
    title:       "أداة [الاسم]",
    description: "أداة تقنية مفتوحة المصدر تساعد المطورين والمنتجين على [الوظيفة].",
    tags:        ["Open Source", "Developer Tools"],
    featured:    false,
    year:        "2022",
    status:      "completed",
    github:      "#",
  },
  {
    id:          "5",
    title:       "منصة [الاسم] B2B",
    description: "حل مؤسسي متكامل لتحويل العمليات التشغيلية رقمياً.",
    tags:        ["Enterprise", "SaaS", "B2B"],
    featured:    true,
    year:        "2022",
    status:      "completed",
    link:        "#",
  },
  {
    id:          "6",
    title:       "مشروع AI [الاسم]",
    description: "تطبيق يستفيد من الذكاء الاصطناعي لحل مشكلة [المجال].",
    tags:        ["AI", "Python", "Product"],
    featured:    false,
    year:        "2024",
    status:      "in-progress",
  },
];

export const skills: Skill[] = [
  // Product
  { name: "استراتيجية المنتج",    level: 95, category: "product" },
  { name: "تصميم تجربة المستخدم", level: 85, category: "product" },
  { name: "أبحاث المستخدم",       level: 88, category: "product" },
  { name: "خارطة الطريق",          level: 92, category: "product" },
  // Technical
  { name: "React / Next.js",     level: 80, category: "technical" },
  { name: "TypeScript",          level: 75, category: "technical" },
  { name: "Cloud Architecture",  level: 70, category: "technical" },
  { name: "Data Analysis",       level: 78, category: "technical" },
  // Leadership
  { name: "قيادة الفرق",          level: 90, category: "leadership" },
  { name: "التفكير الاستراتيجي",   level: 92, category: "leadership" },
  { name: "إدارة أصحاب المصلحة",  level: 87, category: "leadership" },
  { name: "ريادة الأعمال",         level: 88, category: "leadership" },
  // Design
  { name: "Figma",               level: 72, category: "design" },
  { name: "Design Systems",      level: 68, category: "design" },
  { name: "Branding",            level: 75, category: "design" },
];

export const blogPosts: BlogPost[] = [
  {
    id:       "1",
    title:    "لماذا يفشل أغلب مديري المنتج في بناء استراتيجية حقيقية؟",
    excerpt:  "الفرق بين مدير المنتج الذي يشحن مميزات ومدير المنتج الذي يبني مستقبل شركته...",
    date:     "مارس ٢٠٢٤",
    readTime: "٧ دقائق",
    tags:     ["Product Management", "Strategy"],
    platform: "linkedin",
    link:     "#",
    featured: true,
  },
  {
    id:       "2",
    title:    "الذكاء الاصطناعي في الشركات السعودية: الواقع والمستقبل",
    excerpt:  "رحلتي في تطبيق حلول الذكاء الاصطناعي في بيئة العمل السعودية وأبرز الدروس المستفادة...",
    date:     "فبراير ٢٠٢٤",
    readTime: "١٠ دقائق",
    tags:     ["AI", "Saudi Tech"],
    platform: "medium",
    link:     "#",
    featured: true,
  },
  {
    id:       "3",
    title:    "كيف بنيت فريق منتج من الصفر في بيئة ناشئة؟",
    excerpt:  "التحديات والدروس من بناء أول فريق منتج ضمن شركة ناشئة بميزانية محدودة...",
    date:     "يناير ٢٠٢٤",
    readTime: "٨ دقائق",
    tags:     ["Team Building", "Startup"],
    platform: "linkedin",
    link:     "#",
    featured: false,
  },
  {
    id:       "4",
    title:    "المستخدم السعودي: خصائصه وكيف تصمم له منتجات تناسبه",
    excerpt:  "دراسة معمقة في سلوك المستخدم السعودي وتوقعاته من المنتجات الرقمية...",
    date:     "ديسمبر ٢٠٢٣",
    readTime: "١٢ دقيقة",
    tags:     ["UX", "Saudi Market"],
    platform: "personal",
    link:     "#",
    featured: false,
  },
];

export const podcasts: Podcast[] = [
  {
    id:          "1",
    title:       "بناء منتجات رقمية تُغيّر السوق",
    show:        "بودكاست [اسم البودكاست]",
    date:        "مارس ٢٠٢٤",
    duration:    "٥٤ دقيقة",
    description: "نقاش حول استراتيجيات بناء المنتجات الرقمية في السوق السعودي والتحديات التي تواجه رواد الأعمال.",
    platform:    "Spotify",
    link:        "#",
  },
  {
    id:          "2",
    title:       "مستقبل التقنية في المملكة",
    show:        "بودكاست [اسم آخر]",
    date:        "يناير ٢٠٢٤",
    duration:    "٤٧ دقيقة",
    description: "حديث عن رؤية ٢٠٣٠ ودور التقنية في تحقيق أهدافها الاقتصادية والاجتماعية.",
    platform:    "SoundCloud",
    link:        "#",
  },
  {
    id:          "3",
    title:       "الريادة في عالم مليء بالتقنية",
    show:        "بودكاست [اسم ثالث]",
    date:        "نوفمبر ٢٠٢٣",
    duration:    "٣٨ دقيقة",
    description: "كيف تنشئ شركة ناشئة تقنية ناجحة في زمن التحول الرقمي المتسارع.",
    platform:    "YouTube",
    link:        "#",
  },
  {
    id:          "4",
    title:       "إدارة المنتج: من المبتدئ للمحترف",
    show:        "بودكاست تقنيتي",
    date:        "سبتمبر ٢٠٢٣",
    duration:    "٦١ دقيقة",
    description: "رحلة كاملة في مجال إدارة المنتج وأبرز المحطات والدروس المستفادة.",
    platform:    "Spotify",
    link:        "#",
  },
];

export const initiatives: Initiative[] = [
  {
    id:          "1",
    title:       "مبادرة [الاسم] لدعم رواد الأعمال",
    description: "مبادرة هادفة لدعم رواد الأعمال الناشئين بالتوجيه والتدريب وفتح الأبواب.",
    role:        "المؤسس والمشرف",
    period:      "٢٠٢٢ – الآن",
    impact:      "١٠٠+ رائد أعمال استفاد من البرنامج",
    tags:        ["ريادة أعمال", "توجيه", "مجتمع"],
    link:        "#",
  },
  {
    id:          "2",
    title:       "برنامج [الاسم] لتطوير المواهب التقنية",
    description: "برنامج تدريبي مكثف يهدف لتطوير كفاءات الشباب السعودي في مجال التقنية والمنتج.",
    role:        "الشريك المؤسس",
    period:      "٢٠٢١ – ٢٠٢٣",
    impact:      "٥٠٠+ متدرب، ٨٠٪ حصلوا على وظائف تقنية",
    tags:        ["تعليم", "تطوير", "تقنية"],
    link:        "#",
  },
  {
    id:          "3",
    title:       "مجتمع [الاسم] لمديري المنتجات",
    description: "أكبر مجتمع عربي متخصص في إدارة المنتج يجمع المحترفين ويتبادل الخبرات.",
    role:        "المؤسس",
    period:      "٢٠٢٠ – الآن",
    impact:      "٣٠٠٠+ عضو نشط",
    tags:        ["مجتمع", "منتج", "شبكة مهنية"],
    link:        "#",
  },
  {
    id:          "4",
    title:       "هاكاثون [الاسم] السنوي",
    description: "فعالية سنوية تجمع المطورين والمصممين لحل تحديات مجتمعية حقيقية بالتقنية.",
    role:        "المنظم والراعي",
    period:      "٢٠١٩ – ٢٠٢٢",
    impact:      "٢٠+ حل تقني أُطلق لمعالجة تحديات مجتمعية",
    tags:        ["هاكاثون", "ابتكار", "مجتمع"],
    link:        "#",
  },
];
